import Testing
import Foundation
import OrgSwift

/// REGRESSION GUARD on `harness/oracle-dump.el`, NOT a correctness proof. Read this docstring
/// before reading a green run here as evidence of anything about org-mode correctness.
///
/// History matters for why this distinction exists: every `conformance/*/
/// expected.json` fixture in this corpus is now GENERATED BY running `oracle-dump.el` against
/// each case's `input.org` (see SCHEMA.md section 9, "RESOLVED: reference-faithful
/// normalization"). Before that regeneration, `expected.json` was hand-authored from the written
/// spec, independent of any live Emacs, and this suite's job was to compare that independent
/// hand-written answer against the oracle's own answer -- a real, non-circular check, and the
/// first-run diff it caught surfaced two genuine `oracle-dump.el` bugs (a spurious "type" key on
/// nested `date`/`rep` objects, and a UTF-8 double-encoding bug in `princ`) plus the reference-
/// faithful design decision itself.
///
/// That independence is gone now that `expected.json` IS the oracle's own output. This suite
/// still runs `oracle-dump.el` fresh on every `input.org` and compares it against the checked-in
/// `expected.json` -- but the oracle is now being compared against a snapshot of itself, so a
/// green run only proves `oracle-dump.el`'s output for these 52 cases has not changed since the
/// fixtures were minted (e.g. across an Emacs/org-mode version bump on CI, or a future edit to
/// this elisp file). It says nothing about whether that output is actually correct org-mode
/// behavior -- that question now belongs entirely to `harness/interpret-data-check.el` (see
/// `InterpretDataRoundTripTests.swift`), which never touches `expected.json` or this oracle's own
/// JSON shape at all, and to human review of `oracle-dump.el` against the org-element source.
///
/// A RED run here is still real, actionable signal: it means `oracle-dump.el`'s output drifted
/// from the answer key checked into the corpus, which is worth investigating (elisp edit,
/// upstream org-mode behavior change) even though a PASS carries no correctness weight on its
/// own. This is why, unlike every parser-facing suite in this project, a failure here is NOT
/// wrapped in `withKnownIssue` -- it does not gate on the pending parser at all.
///
/// Skipped entirely (not failed) without a local Emacs 27+ (`json-serialize`) on `PATH`, same as
/// `OracleDiffTests`. Per case, if `oracle-dump.el` itself fails for that file (script bug,
/// unmapped node type, decode failure), that case skips gracefully rather than failing.
@Suite(
    "oracle-dump.el regression guard (NOT a correctness proof -- see docstring)",
    .enabled(if: HarnessSupport.emacsAvailable)
)
struct OracleConformanceCrossCheckTests {

    static let cases: [CorpusLoader.ConformanceCase] = (try? CorpusLoader.conformanceCases()) ?? []

    // `CorpusLoader.ConformanceCase: CustomTestStringConvertible` is already declared in
    // ConformanceTests.swift (same module) -- not re-declared here to avoid a duplicate
    // conformance.

    @Test("oracle-dump.el's output for this case has not drifted from its own checked-in fixture", arguments: cases)
    func oracleMatchesItsOwnRegeneratedFixture(_ testCase: CorpusLoader.ConformanceCase) throws {
        let inputURL = HarnessSupport.conformanceInputURL(for: testCase.name)
        let oracleTree: OrgJSON
        do {
            oracleTree = try HarnessSupport.runOracleDump(on: inputURL)
        } catch {
            // No oracle answer for this case yet (script bug, unmapped node type, decode
            // failure, ...) -- a gap in oracle-dump.el, not evidence expected.json is wrong.
            return
        }
        #expect(
            oracleTree == testCase.expected,
            "\(testCase.name): oracle-dump.el's live output no longer matches the checked-in expected.json it originally generated -- investigate the elisp change or Emacs/org-mode version drift; this does NOT mean expected.json is independently wrong, since it was generated from this same oracle"
        )
    }
}
