;;; oracle-dump.el --- Dump org-element's own parse of a file as orgswift's normalized JSON  -*- lexical-binding: t; -*-

;; STATUS (updated after the first real run, Emacs 30.2 / org-mode 9.7.11):
;; this file HAS been run for real, not left untested. A full sweep against
;; all 52 conformance/*/input.org cases produces 52 valid JSON documents, 0
;; process failures, 0 stderr warnings, and 0 "unmapped org-element type"
;; messages (harness/verify-corpus.sh reports the same result: 52/52 PASS).
;; SCHEMA.md section 9 records the first live run in more detail, including
;; two real bugs that run caught and this file has since fixed (a spurious
;; "type" key on nested date/rep objects, and a UTF-8 double-encoding bug in
;; the `princ' step - see `org-swift-dump's own docstring below for that
;; second one).
;;
;; What that clean run does NOT prove: every conformance/*/expected.json
;; fixture in this repo was GENERATED by running this file against that
;; case's input.org (see SCHEMA.md section 9, "RESOLVED: reference-faithful
;; normalization"). So a clean run here is a NON-DRIFT regression guard, not
;; an independent correctness proof - it confirms this file's output has not
;; changed since it minted the answer key it is compared against, not that
;; the answer key is correct org-mode behavior. A mistyped property name or a
;; mis-mapped field, introduced consistently, would produce a self-consistent
;; but WRONG fixture, and nothing in this repo's test suite would catch it:
;; not Tests/OrgSwiftTests/OracleConformanceCrossCheckTests.swift (compares
;; this file against its own generated output), not harness/verify-corpus.sh
;; (same comparison, shelled out instead of run through Swift Testing). The
;; one non-circular signal that exists is harness/interpret-data-check.el,
;; which never touches this file's JSON shape at all (see that script's own
;; header, and SCHEMA.md section 9's "Independent, non-circular support"
;; paragraph) - it catches missing or extra BYTES, not a wrong property NAME
;; or a value mapped onto the wrong schema field.
;;
;; The compensating control for that gap is a focused, line-by-line human
;; review of this file's per-type property mappings (the `pcase' inside
;; `org-swift--dump-typed-node' below) against org-element.el's own source,
;; one type at a time. That review has NOT been done yet. Until it has, judge
;; each per-type mapping below on its own merits, not as "must be right
;; because the suite is green": the inline "UNTESTED:" comments below flag the
;; specific mappings no conformance fixture exercises yet, and were swept
;; after the first live run to drop any that the 52-case corpus now actually
;; confirms - the ABSENCE of such a comment on a mapping means a corpus case
;; exercises it and it matched, not that it has passed the still-outstanding
;; source-level review.
;;
;; PENDING REGENERATION (added during the oracle-auditor pass, not yet
;; resolved as of this comment): the "52/52 PASS" claim above describes this
;; file's behavior BEFORE a round of confirmed-bug fixes, deliberately
;; scoped narrow - fix what is broken, complete what this schema already
;; claims, add no new type claims:
;;   - A crash on any `CLOCK:' line (the generic fallback assumed :value was
;;     always a string or nil; a clock's :value is a whole timestamp node).
;;     Fixed at the root: the fallback now only ever hands a STRING :value
;;     to the JSON layer, everything else is omitted with a warning rather
;;     than guessed at. `clock' itself stays deliberately unmapped - no new
;;     node type was added for it.
;;   - A fabricated `affiliated' key on `entity' and other object nodes
;;     (`org-swift--affiliated' now gates on `(memq type
;;     org-element-all-elements)').
;;   - A silently emptied `table.el' ASCII table (`table' now checks :type;
;;     `table.el' warns loudly and emits its raw text under `value' instead
;;     of silently producing `children: []' - ordinary `org' tables are
;;     completely untouched, byte-identical to before).
;;   - A missing `preBlank' on the three node types this schema maps that
;;     org-element tracks :pre-blank on: `headline', `item',
;;     `footnote-definition' (org-element tracks a fourth, `inlinetask', but
;;     that type is not one of this schema's mapped types at all - see
;;     schema/README.md's preBlank section). Confirmed live paragraph/
;;     plain-list do not track :pre-blank at all; emitting it there would
;;     fabricate a field, the same class of error the affiliated-keyword fix
;;     above corrects.
;;   - An under-implemented `affiliated' (HEADER/PLOT/RESULTS/ATTR_* were
;;     unimplemented; multiple `#+CAPTION:' lines collapsed to the last one
;;     only).
;;   - A dropped `:diary-sexp' payload on diary timestamps (present only
;;     for `kind: "diary"', omitted - not null - everywhere else, for the
;;     same not-tracked-there reason as `preBlank').
;;   - A `text' node that inconsistently carried `postBlank' depending on
;;     whether it came from a hard line break or ordinary text.
;; Those are now fixed, which means this file's output has genuinely
;; changed for `headline'/`item' nodes (the `preBlank' addition) -
;; `conformance/*/expected.json' was generated from the OLD behavior and
;; has deliberately NOT been regenerated yet (that is a separate, reviewed
;; step, not automatic). Every other fix above is predicted to touch ZERO
;; of the 52 checked-in fixtures, since the corpus contains no `CLOCK:'
;; line, no `entity', no `table.el' table, no HEADER/PLOT/RESULTS/ATTR_*
;; keyword, no repeated `#+CAPTION:', and no diary timestamp.
;; `harness/verify-corpus.sh' will report mismatches against the corpus
;; until regeneration happens - that is the expected, intended signal that
;; the `preBlank' fix took effect, not a new bug; any mismatch beyond a
;; `preBlank' addition on a `headline'/`item' node is NOT expected and is
;; worth investigating before trusting this pass. Once regeneration is
;; reviewed and lands, this whole STATUS block should be re-verified
;; against a fresh clean run and updated to match, rather than trusted as
;; still describing current behavior.
;;
;; Purpose: this is the answer key for Layer 3 (OracleDiffTests.swift). It
;; asks Emacs's own `org-element-parse-buffer' to parse a file, then walks
;; that tree and re-emits it as the exact JSON shape documented in
;; SCHEMA.md - so orgswift's parser can be checked against real org-mode
;; behavior, not just against our own hand-written conformance fixtures.
;;
;; Usage (from the repo root):
;;   emacs --batch -Q -l harness/oracle-dump.el --eval '(org-swift-dump "path/to/file.org")'
;;
;; Prints one JSON document to stdout. Warnings (e.g. an org-element node
;; type this script does not yet know how to map) go to stderr via
;; `message', which in `--batch' mode never touches stdout - so stdout stays
;; parseable JSON even when something is off.
;;
;; Requires Emacs 27+ (native JSON support, `json-serialize'/`json-parse-string')
;; and the `org' package, which ships with modern Emacs. `-Q' skips init files
;; and site-lisp but still has org built in, so no extra `package-install' is
;; needed.

(unless (fboundp 'json-serialize)
  (error "oracle-dump.el requires Emacs 27+ with native JSON support (json-serialize)"))

(require 'org)

;; ---------------------------------------------------------------------------
;; JSON value construction.
;;
;; `json-serialize' (Emacs's native, libjansson-backed encoder) has a real
;; nil/false/empty-array ambiguity in plain Lisp: an empty list `()' and Lisp
;; `nil' are the same object, and by default nil serializes as `[]', not as
;; `false' or `null'. To keep every JSON shape unambiguous, this script never
;; hands `json-serialize' a bare Lisp list or `nil':
;;   - JSON object  -> an Emacs hash-table (`org-swift--make-node' below)
;;   - JSON array   -> an Emacs vector, always, even when empty (`[]' as a
;;                      vector serializes correctly; `[]' as `nil' would not
;;                      be distinguishable from "false" if we ever used nil
;;                      for false elsewhere)
;;   - JSON null    -> the keyword `:null' (json-serialize's default
;;                      `:null-object')
;;   - JSON false   -> the keyword `:false' (json-serialize's default
;;                      `:false-object'); JSON true is Lisp `t'
;;   - JSON string/number -> ordinary Lisp string/integer/float
;; ---------------------------------------------------------------------------

(defconst org-swift--omit 'org-swift--omit
  "Sentinel value: a key/value pair carrying this as its value is dropped
entirely from the object being built, rather than emitted as null. Used for
schema keys that must be ABSENT when not applicable (e.g. `affiliated' on an
element with no affiliated keywords, or `children' on a non-inline
footnote-reference) as opposed to keys that are always present but may be
null (e.g. `todo' on a headline).")

(defun org-swift--json-array (list)
  "Convert LIST (a Lisp list of already-converted JSON values) into a JSON
array. Always a vector, even for an empty LIST - see the ambiguity note
above."
  (apply #'vector list))

(defun org-swift--make-node (type-string kvs)
  "Build a JSON object (a hash-table) with \"type\" = TYPE-STRING plus the
key/value pairs in KVS, an alist of (KEY-STRING . JSON-VALUE). Any pair whose
value is `org-swift--omit' is dropped entirely."
  (let ((h (make-hash-table :test 'equal)))
    (puthash "type" type-string h)
    (dolist (kv kvs)
      (unless (eq (cdr kv) org-swift--omit)
        (puthash (car kv) (cdr kv) h)))
    h))

(defun org-swift--plain-object (kvs)
  "Build a JSON object (a hash-table) with ONLY the key/value pairs in KVS -
no auto-added \"type\" key. For the handful of schema shapes that are plain
nested values, not tagged schema nodes: SCHEMA.md's `date' (inside a
timestamp's start/end) has no \"type\" field at all, unlike every top-level
node type. Confirmed live against Emacs: reusing `org-swift--make-node' here
put a spurious `\"type\": \"date\"' key into every timestamp's start/end,
which caused a real diff against every timestamp-bearing expected.json
fixture on first run - this helper is that fix."
  (let ((h (make-hash-table :test 'equal)))
    (dolist (kv kvs)
      (unless (eq (cdr kv) org-swift--omit)
        (puthash (car kv) (cdr kv) h)))
    h))

;; ---------------------------------------------------------------------------
;; org-element type name -> orgswift schema type name.
;;
;; Most org-element type symbols match our schema's type strings exactly
;; (`symbol-name' of the org-element type IS the schema type, e.g. `paragraph'
;; -> "paragraph", `table-row' -> "table-row"). Only a handful differ; this
;; alist lists ONLY the renames. Everything else falls through to
;; `symbol-name' in `org-swift--schema-type-name'.
;; ---------------------------------------------------------------------------

(defconst org-swift--type-renames
  '((org-data . "document")           ; org-element's parse-tree root
    (plain-list . "list")             ; SCHEMA.md calls this `list', not `plain-list'
    (strike-through . "strikethrough")) ; SCHEMA.md has no hyphen
  "Alist of (ORG-ELEMENT-TYPE-SYMBOL . SCHEMA-TYPE-STRING) for the few org-element
type names that do not match our schema's type string verbatim.")

(defun org-swift--schema-type-name (org-element-type)
  "Map an org-element type SYMBOL to its orgswift schema type STRING."
  (or (cdr (assq org-element-type org-swift--type-renames))
      (symbol-name org-element-type)))

;; ---------------------------------------------------------------------------
;; Small property helpers.
;; ---------------------------------------------------------------------------

(defun org-swift--prop (node key)
  "Shorthand for `(org-element-property KEY NODE)'."
  (org-element-property key node))

(defun org-swift--str-or-null (v)
  "A string property V, or `:null' when V is nil."
  (or v :null))

(defun org-swift--bool (v)
  "V (any Lisp truthy/nil value) as a JSON boolean: `t' or `:false'."
  (if v t :false))

(defun org-swift--symbol-or-null (v)
  "Symbol property V (e.g. `on'/`off'/`trans'/`standard'/`rule') as its
`symbol-name' string, or `:null' when V is nil."
  (if v (symbol-name v) :null))

(defun org-swift--dump-children (node)
  "The JSON array for NODE's ordinary element/object children (its
`org-element-contents'), each converted via `org-swift--node-json'. This is
the generic \"children\" value used by every container type in section 4 of
SCHEMA.md whose empty case is `[]', not null."
  (org-swift--json-array (mapcar #'org-swift--node-json (org-element-contents node))))

(defun org-swift--dump-secondary (val)
  "VAL is a secondary-string property (`:title' on a headline, `:tag' on a
descriptive-list item): a list of already-parsed objects under
`org-element-parse-buffer's default (full) parse granularity.

UNTESTED fallback, still genuinely untested after the first live run: every
title/tag in the 52-case conformance corpus comes back already parsed under
`org-element-parse-buffer's default granularity, so this branch (VAL somehow
still a raw, unparsed string - a different granularity or Emacs version) has
never actually executed against real Emacs. It wraps such a VAL as one
literal `text' node rather than crashing, since org-element--parse-objects is
not called here. If real output ever shows a literal string where markup was
expected in a title, this is the first place to look."
  (cond
   ((null val) (org-swift--json-array '()))
   ((stringp val) (org-swift--json-array (list (org-swift--make-node "text" `(("value" . ,val))))))
   (t (org-swift--json-array (mapcar #'org-swift--node-json val)))))

(defun org-swift--dump-secondary-or-null (val)
  "Like `org-swift--dump-secondary', but nil means JSON null, not an empty
array - for fields SCHEMA.md documents as \"[object-nodes] or null\" (link
description, item tag), where null and empty are meaningfully different."
  (if val (org-swift--dump-secondary val) :null))

(defun org-swift--link-description (node)
  "Per SCHEMA.md: a link's description is `[object-nodes]' when present, or
JSON `null' (NOT an empty array) when the link has no description - distinct
from every other \"children\"-shaped field, which uses `[]' for \"none\"."
  (let ((contents (org-element-contents node)))
    (if contents (org-swift--json-array (mapcar #'org-swift--node-json contents)) :null)))

;; ---------------------------------------------------------------------------
;; Timestamps.
;;
;; CONFIRMED for the standard (non-diary) case: the regex-scrape approach
;; below is exercised, on both the `start' and `end' side of a range, by
;; conformance/timestamp-active-range and every other timestamp-* fixture,
;; and matches on all of them in the 52-case clean run. `:dayname' itself is
;; not a documented org-element property as far as this script's author could
;; confirm without a running Emacs, and real org-mode tolerates a dayname
;; token that does not even match the actual weekday (e.g. `<2026-01-01
;; Blah>' parses fine), so computing the "correct" weekday from y/m/d would
;; NOT reproduce what the source text actually says - that is why this
;; scrapes the dayname token straight out of `:raw-value' via regex instead,
;; tracking whatever the source text contains rather than what the calendar
;; says. STILL UNTESTED: the diary-timestamp case (`<%%(SEXP)>'), which has no
;; y/m/d/dayname at all - out of scope for the Layer 1 corpus per SCHEMA.md
;; section 9, and not exercised here either. If a non-diary case is ever
;; wrong, check `:raw-value`'s actual format first with `(message "%S"
;; (org-element-property :raw-value ts))'.
;; ---------------------------------------------------------------------------

(defconst org-swift--dayname-re
  "<?\\[?[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\} +\\([A-Za-z]+\\)"
  "Matches the dayname token (group 1) right after the YYYY-MM-DD date in one
half of a timestamp's `:raw-value', e.g. the \"Thu\" in \"<2026-01-15 Thu>\".")

(defun org-swift--timestamp-dayname (node which)
  "Extract the dayname token for the start (WHICH = `start') or end
(WHICH = `end') half of NODE's `:raw-value', or `:null' if none is present
(org-mode does not require a dayname). For a range, the end half is whatever
follows the `--' separator; for a single timestamp, `end' always returns
`:null' since there is nothing to extract from."
  (let* ((raw (org-swift--prop node :raw-value))
         (halves (and raw (split-string raw "--"))))
    (pcase which
      ('start (if (and halves (string-match org-swift--dayname-re (car halves)))
                  (match-string 1 (car halves))
                :null))
      ('end (if (and halves (cadr halves) (string-match org-swift--dayname-re (cadr halves)))
                (match-string 1 (cadr halves))
              :null)))))

(defun org-swift--timestamp-date (node which)
  "Build a `date' object (SCHEMA.md section 4, Timestamps) from NODE's
`:year-WHICH' / `:month-WHICH' / `:day-WHICH' / `:hour-WHICH' /
`:minute-WHICH' properties, WHICH being `start' or `end'. Returns `:null'
only when the year property is genuinely absent.

DO NOT REMOVE THE `is-range' GUARD AT THE CALL SITE. An earlier version of
this docstring claimed the year is absent for WHICH = `end' on a non-range
timestamp, which made that guard look redundant. It is not, and the claim
was false: org-element populates the full `:*-end' set on non-range
timestamps too - a plain `<2026-01-01 Thu>' carries `:year-end' 2026,
`:month-end' 1, `:day-end' 1, confirmed live against Emacs 30.2. Asked for
`end' there, this function returns a REAL date, not `:null'.

What actually keeps `end' null on a non-range timestamp is
`org-swift--dump-timestamp', which only calls this function for `end' when
`is-range' is non-nil and hardcodes `:null' otherwise. Delete that guard on
the strength of a comment and every non-range timestamp silently gains an
`end' duplicating its `start', changing every timestamp fixture in the
corpus and corrupting the published answer key.

Audit finding 20. Kept verbose deliberately: the same class of defect - a
comment asserting an invariant nothing enforces - is what produced the
`CLOCK:' crash (see the fallback's own history)."
  (let ((year (org-swift--prop node (intern (format ":year-%s" which)))))
    (if (not year)
        :null
      (org-swift--plain-object
        `(("year" . ,year)
          ("month" . ,(org-swift--prop node (intern (format ":month-%s" which))))
          ("day" . ,(org-swift--prop node (intern (format ":day-%s" which))))
          ("dayname" . ,(org-swift--timestamp-dayname node which))
          ("hour" . ,(org-swift--str-or-null (org-swift--prop node (intern (format ":hour-%s" which)))))
          ("minute" . ,(org-swift--str-or-null (org-swift--prop node (intern (format ":minute-%s" which))))))))))

(defconst org-swift--repeater-type-map
  '((cumulate . "+") (catch-up . "++") (restart . ".+"))
  "org-element `:repeater-type' symbol -> SCHEMA.md `rep.type' string.")

(defconst org-swift--warning-type-map
  '((all . "-") (first . "--"))
  "org-element `:warning-type' symbol -> SCHEMA.md `rep.type' string (delay).")

(defconst org-swift--unit-map
  '((hour . "h") (day . "d") (week . "w") (month . "m") (year . "y"))
  "org-element `:repeater-unit'/`:warning-unit' symbol -> SCHEMA.md `rep.unit'.")

(defun org-swift--rep (node type-prop type-map value-prop unit-prop)
  "Build a `rep' object (SCHEMA.md: {type, value, unit} - unlike `date', `rep'
DOES have a \"type\" key, just not one naming a schema node: its value is the
repeater/delay kind string, e.g. \"+\"/\"++\"/\".+\" or \"-\"/\"--\") from
NODE's TYPE-PROP (mapped through TYPE-MAP), VALUE-PROP, and UNIT-PROP (mapped
through `org-swift--unit-map'), or `:null' when TYPE-PROP is absent (no
repeater/delay at all). Built with `org-swift--plain-object', not
`org-swift--make-node': this happened to come out correct even through
`make-node' (the KVS \"type\" entry overwrote make-node's own auto-added
\"type\" key in the hash-table build order), but relying on that overwrite
order was fragile and confusing - `date' right above needed the same
un-tagged treatment for a real reason, so both now use the same explicit,
not-accidentally-correct path."
  (let ((type-sym (org-swift--prop node type-prop)))
    (if (not type-sym)
        :null
      (org-swift--plain-object
        `(("type" . ,(or (cdr (assq type-sym type-map)) (symbol-name type-sym)))
          ("value" . ,(org-swift--prop node value-prop))
          ("unit" . ,(let ((u (org-swift--prop node unit-prop)))
                       (or (cdr (assq u org-swift--unit-map)) (and u (symbol-name u))))))))))

(defun org-swift--dump-timestamp (node)
  (let* ((kind-sym (org-swift--prop node :type)) ; active/inactive/active-range/inactive-range/diary
         (kind (symbol-name kind-sym))
         (is-range (memq kind-sym '(active-range inactive-range))))
    (org-swift--make-node "timestamp"
      `(("kind" . ,kind)
        ("start" . ,(org-swift--timestamp-date node 'start))
        ("end" . ,(if is-range (org-swift--timestamp-date node 'end) :null))
        ("repeater" . ,(org-swift--rep node :repeater-type org-swift--repeater-type-map
                                       :repeater-value :repeater-unit))
        ("delay" . ,(org-swift--rep node :warning-type org-swift--warning-type-map
                                    :warning-value :warning-unit))
        ;; :diary-sexp is the raw `(SEXP ...)' text of a diary timestamp
        ;; (`<%%(SEXP)>'), e.g. "(diary-float 1 3 2)" - confirmed live
        ;; against Emacs 30.2. Confirmed equally live: every OTHER timestamp
        ;; kind has no :diary-sexp property AT ALL (org-element never sets
        ;; it - not "sets it to nil", genuinely absent, exactly the same
        ;; absence :pre-blank has on paragraph/plain-list). So this key is
        ;; OMITTED entirely (via `org-swift--omit', not emitted as `null')
        ;; for the five non-diary kinds, and present as a string only for
        ;; `kind: "diary"' - the only field that carries any payload at all
        ;; for that kind, whose :year-start etc. are all nil (see
        ;; `org-swift--timestamp-date'). An earlier version of this
        ;; function read every other diary-relevant property but never
        ;; this one, so a diary timestamp's entire payload was silently
        ;; dropped - `kind: "diary"` with every other field null and
        ;; nothing to show what sexp the source actually contained. A
        ;; still-earlier version of THIS fix emitted `diarySexp: null'
        ;; unconditionally on every kind, mirroring `postBlank' - wrong for
        ;; the same reason a blanket `preBlank' would be: it fabricates a
        ;; field org-element does not track on the other five kinds.
        ("diarySexp" . ,(if (eq kind-sym 'diary)
                             (org-swift--prop node :diary-sexp)
                           org-swift--omit))))))

;; ---------------------------------------------------------------------------
;; Affiliated keywords (SCHEMA.md section 5).
;;
;; All five affiliated keyword families org-element recognizes are
;; implemented: NAME, CAPTION, HEADER, PLOT, RESULTS, plus the open-ended
;; ATTR_BACKEND family (ATTR_HTML, ATTR_LATEX, any user-chosen backend name).
;; Every shape below was confirmed live against Emacs 30.2 with constructed
;; test files, not assumed from documentation - see each helper's own
;; docstring for what was actually observed.
;; ---------------------------------------------------------------------------

(defun org-swift--attr-keyword-keys (node)
  "Return the list of :attr_BACKEND property-key SYMBOLS present on NODE's own
properties, e.g. (:attr_html :attr_latex) for a node carrying `#+ATTR_HTML:'
and `#+ATTR_LATEX:' lines. `#+ATTR_BACKEND:' is open-ended - any backend name
is legal syntax - so org-element does not expose these through named
accessors the way :name/:caption/:header/:plot/:results are; the only way to
discover which ones a given node actually carries is to walk its own
properties plist. `(cadr node)' is that plist - the `(TYPE PROPERTIES-PLIST
. CONTENTS)' element/object shape org-element's own manual documents - and is
used here ONLY to discover which keys exist; the actual value for each
discovered key is still read back through `org-element-property' (via
`org-swift--prop'), never through this raw plist directly. Confirmed live
against Emacs 30.2: a table node with `#+ATTR_HTML:' and `#+ATTR_LATEX:'
lines shows exactly `(:attr_html :attr_latex)' via this walk, matching
`org-element-property' reads of the same two keys."
  (let ((plist (cadr node))
        (keys nil))
    (while plist
      (let ((key (car plist)))
        (when (and (keywordp key) (string-prefix-p ":attr_" (symbol-name key)))
          (push key keys)))
      (setq plist (cddr plist)))
    (nreverse keys)))

(defun org-swift--dump-caption (caption)
  "CAPTION's own value shape (SCHEMA.md section 5, `affiliated.CAPTION'):
`:caption' is a LIST of entries, one per `#+CAPTION:' line, in source order -
CAPTION is in `org-element-multiple-keywords', confirmed live: two
`#+CAPTION:' lines before one table produced a genuine two-entry list, in
order, not the single last-one-wins value an earlier version of this
function kept via `(caar (last caption))'. Each entry is itself a 2-element
list `(LONG SHORT)' - CAPTION is ALSO in `org-element-dual-keywords':
LONG is always a list of parsed object-nodes (even for a single resulting
object, e.g. plain text with no markup still comes back as a 1-element
list); SHORT is a single raw, propertized STRING when the
`#+CAPTION[short]: long' dual form was used, or absent, making the entry a
1-element list, otherwise. Confirmed live both ways: `(cdr entry)' is always
a proper (nil-terminated) list, never a dotted pair, so `(cadr entry)' safely
reads SHORT (or nil) either way - CAPTION's own dual form does not use the
dotted-pair shape RESULTS below does."
  (org-swift--json-array
    (mapcar
      (lambda (entry)
        (org-swift--plain-object
          `(("long" . ,(org-swift--dump-secondary (car entry)))
            ("short" . ,(org-swift--str-or-null (cadr entry))))))
      caption)))

(defun org-swift--dump-results (results)
  "RESULTS's own value shape (SCHEMA.md section 5, `affiliated.RESULTS'):
`:results' is in `org-element-dual-keywords' too, but unlike CAPTION its dual
form is a genuine dotted pair, not a proper list. Confirmed live: a plain
`#+RESULTS: name' produces `(VALUE . nil)'; the dual `#+RESULTS[hash]: name'
form produces `(VALUE . HASH)' with an explicit dot, both VALUE and HASH raw,
unparsed strings (RESULTS is not in `org-element-parsed-keywords'). Always
emitted here as one object shape, `{\"value\": ..., \"hash\": ...}', whether
or not a hash was written, rather than a string-or-object union that would
force every consumer of this schema to branch on which form showed up."
  (org-swift--plain-object
    `(("value" . ,(car results))
      ("hash" . ,(org-swift--str-or-null (cdr results))))))

(defun org-swift--affiliated (node type)
  "Build the `affiliated' key's value (SCHEMA.md section 5) for NODE (whose
raw org-element type symbol is TYPE) - or `org-swift--omit' when NODE carries
no affiliated keyword, or is not eligible to carry one at all.

The eligibility gate below fixes a real, confirmed bug, not a stylistic
addition. Affiliated keywords attach to ELEMENTS only, never to objects, per
org-syntax.html and per org-element's own source: `org-element-all-elements'
and `org-element-all-objects' are two disjoint constants org-element itself
maintains and exports. An earlier version of this function had no such gate
and read :name/:caption off every node type unconditionally, on the reasoning
that the relevant properties simply would not exist on object nodes -
confirmed live that reasoning was wrong: a bare `\\alpha' `entity' object (an
OBJECT, not an element) has its OWN `:name' property (\"alpha\", the entity's
own identifying name, set by `org-element-entity-parser' - nothing to do
with any `#+NAME:' line), and the old, ungated code emitted
`{\"affiliated\": {\"NAME\": \"alpha\"}}' for it, fabricating an affiliated
keyword that was never in the source at all. Checking
`(memq type org-element-all-elements)' first is exactly the invariant this
function always claimed to rely on but never actually enforced; it also
correctly restores `keyword' (an element) to eligibility after an even
earlier, hand-picked allowlist wrongly excluded it - confirmed live via
`#+NAME: t4' immediately before `#+SUBTITLE: value' producing a real
`keyword' node with `affiliated: {\"NAME\": \"t4\"}'."
  (if (not (memq type org-element-all-elements))
      org-swift--omit
    (let ((h (make-hash-table :test 'equal))
          (any nil))
      (let ((name (org-swift--prop node :name)))
        (when name (puthash "NAME" name h) (setq any t)))
      (let ((caption (org-swift--prop node :caption)))
        (when caption
          (puthash "CAPTION" (org-swift--dump-caption caption) h)
          (setq any t)))
      (let ((header (org-swift--prop node :header)))
        ;; :header is in `org-element-multiple-keywords' too (like CAPTION)
        ;; but NOT in `org-element-dual-keywords': confirmed live, it comes
        ;; back as a plain list of raw strings, one per `#+HEADER:' line, in
        ;; source order, with no short/long split.
        (when header (puthash "HEADER" (org-swift--json-array header) h) (setq any t)))
      (let ((plot (org-swift--prop node :plot)))
        ;; :plot is neither multiple nor dual: confirmed live, a single raw
        ;; string.
        (when plot (puthash "PLOT" plot h) (setq any t)))
      (let ((results (org-swift--prop node :results)))
        (when results (puthash "RESULTS" (org-swift--dump-results results) h) (setq any t)))
      (dolist (attr-key (org-swift--attr-keyword-keys node))
        ;; Confirmed live: repeating the SAME `#+ATTR_HTML:' line twice
        ;; accumulates into a list of strings, exactly like HEADER, even
        ;; though ATTR_* is not itself listed in
        ;; `org-element-multiple-keywords' (that alist only names the
        ;; canonical keywords; ATTR_* is handled by separate, backend-name-
        ;; agnostic logic in org-element that always produces a list).
        (let ((value (org-swift--prop node attr-key)))
          (when value
            (puthash (upcase (substring (symbol-name attr-key) 1)) (org-swift--json-array value) h)
            (setq any t))))
      (if any h org-swift--omit))))

;; ---------------------------------------------------------------------------
;; Per-type dispatch. TYPE is the raw org-element symbol (before renaming);
;; SCHEMA-TYPE is the already-renamed string used as the JSON "type" value.
;; ---------------------------------------------------------------------------

(defun org-swift--dump-typed-node (schema-type type node)
  (let ((base
         (pcase type
           ('org-data (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('headline
            (org-swift--make-node schema-type
              `(("level" . ,(org-swift--prop node :level))
                ("todo" . ,(org-swift--str-or-null (org-swift--prop node :todo-keyword)))
                ("priority" . ,(let ((p (org-swift--prop node :priority)))
                                 ;; CONFIRMED via conformance/easy-priority-and-
                                 ;; tags-headline (`[#A]' -> "priority": "A" in
                                 ;; the 52-case clean run): org-element stores
                                 ;; :priority as a character code (e.g. ?A =
                                 ;; 65), not a string, so char-to-string here
                                 ;; is required, not optional.
                                 (if p (char-to-string p) :null)))
                ("commented" . ,(org-swift--bool (org-swift--prop node :commentedp)))
                ("tags" . ,(org-swift--json-array (org-swift--prop node :tags)))
                ("title" . ,(org-swift--dump-secondary (org-swift--prop node :title)))
                ;; :pre-blank holds the blank line count between the
                ;; headline's own line and its first child - bytes that
                ;; exist nowhere else in the tree, so dropping them makes
                ;; them unrecoverable. org-element sets :pre-blank on four
                ;; types total: headline, item, footnote-definition (all
                ;; three mapped below and emitted - see each type's own
                ;; :pre-blank comment), and inlinetask (NOT one of this
                ;; schema's mapped types - see schema/README.md's preBlank
                ;; section). Confirmed live it is exercised in the shipped
                ;; real-world corpus (headline case in real/org-mode-samples).
                ("preBlank" . ,(org-swift--prop node :pre-blank))
                ("children" . ,(org-swift--dump-children node)))))

           ('section (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('planning
            (org-swift--make-node schema-type
              `(("scheduled" . ,(org-swift--node-json (org-swift--prop node :scheduled)))
                ("deadline" . ,(org-swift--node-json (org-swift--prop node :deadline)))
                ("closed" . ,(org-swift--node-json (org-swift--prop node :closed))))))

           ('property-drawer (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('node-property
            (org-swift--make-node schema-type
              `(("key" . ,(org-swift--prop node :key))
                ("value" . ,(org-swift--str-or-null (org-swift--prop node :value))))))

           ('drawer
            (org-swift--make-node schema-type
              `(("name" . ,(org-swift--prop node :drawer-name))
                ("children" . ,(org-swift--dump-children node)))))

           ('dynamic-block
            ;; `#+BEGIN: NAME ARGS...#+END:' - :block-name is the NAME token;
            ;; :arguments is the raw, unparsed rest-of-line text after NAME
            ;; (org-element does not tokenize dynamic-block arguments itself,
            ;; since their syntax is defined per-block-type by whatever
            ;; function generates that block's content, not by org-element).
            (org-swift--make-node schema-type
              `(("blockName" . ,(org-swift--prop node :block-name))
                ("arguments" . ,(org-swift--str-or-null (org-swift--prop node :arguments)))
                ("children" . ,(org-swift--dump-children node)))))

           ((or 'quote-block 'center-block)
            (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('verse-block (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('paragraph (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ((or 'bold 'italic 'underline 'strike-through)
            (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ((or 'code 'verbatim)
            (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ('latex-fragment
            ;; A leaf object, same shape as code/verbatim: `:value' is the
            ;; fragment's own literal text, e.g. "$x^2$" or "\(x^2\)",
            ;; delimiters included - org-element does not strip them for
            ;; latex-fragment the way it does for code/verbatim's markers.
            (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ('link
            (org-swift--make-node schema-type
              `(("linkType" . ,(pcase (org-swift--prop node :format)
                                  ('bracket "regular")
                                  ('angle "angle")
                                  ('plain "plain")
                                  (other (and other (symbol-name other)))))
                ;; :path is PROTOCOL-STRIPPED (org-element splits the link
                ;; target into :type = "https" and :path = "//example.com"
                ;; for [[https://example.com]]) - NOT what SCHEMA.md's `path'
                ;; means ("the raw link target, without brackets/protocol
                ;; wrapper stripped further"). :raw-link is the delimiter-
                ;; stripped-but-protocol-intact form ("https://example.com"),
                ;; matching every Layer 1 link fixture and SCHEMA.md exactly.
                ;; Caught by reviewer before the first real Emacs run - fixed
                ;; here, not worked around downstream.
                ("path" . ,(org-swift--prop node :raw-link))
                ("description" . ,(org-swift--link-description node)))))

           ('plain-list (org-swift--make-node schema-type
              `(("kind" . ,(symbol-name (org-swift--prop node :type)))
                ("children" . ,(org-swift--dump-children node)))))

           ('item
            (org-swift--make-node schema-type
              `(("bullet" . ,(string-trim-right (or (org-swift--prop node :bullet) "")))
                ("checkbox" . ,(org-swift--symbol-or-null (org-swift--prop node :checkbox)))
                ("tag" . ,(org-swift--dump-secondary-or-null (org-swift--prop node :tag)))
                ;; Same :pre-blank rationale as headline above - org-element
                ;; sets it on item too (a blank line between the bullet and
                ;; its first line of content); confirmed exercised in the
                ;; shipped real-world corpus (10 items in
                ;; real/doomemacs-docs).
                ("preBlank" . ,(org-swift--prop node :pre-blank))
                ("children" . ,(org-swift--dump-children node)))))

           ('src-block
            ;; CONFIRMED via conformance/block-src-literal and block-src-
            ;; with-params in the 52-case clean run. An earlier version of
            ;; this comment assumed org-element's :value EXCLUDED the
            ;; trailing newline right before the #+end_src line - that
            ;; assumption predates SCHEMA.md's reference-faithful resolution
            ;; (section 1) and was simply wrong: passing :value straight
            ;; through, unmodified, DOES include the trailing "\n" after the
            ;; last content line (a one-line body is "let x = 1\n", not
            ;; "let x = 1"), and that is the correct, checked-in convention,
            ;; not a bug to fix. `example-block' below shares the identical
            ;; convention and is equally confirmed
            ;; (conformance/block-example-literal). `comment-block' is NOT
            ;; exercised by any conformance fixture yet, so whether it needs
            ;; the same trailing-newline handling remains genuinely untested.
            (org-swift--make-node schema-type
              `(("language" . ,(org-swift--str-or-null (org-swift--prop node :language)))
                ("params" . ,(org-swift--str-or-null (org-swift--prop node :parameters)))
                ("value" . ,(org-swift--prop node :value)))))

           ('example-block (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ('export-block
            ;; CONFIRMED live against Emacs 30.2 (conformance/
            ;; block-export-html): both risks originally flagged here did not
            ;; materialize. The backend name does live on :type, and it comes
            ;; back as an ordinary string ("HTML", upcased by org-element),
            ;; not a symbol - `org-swift--str-or-null` needed no `symbol-name`
            ;; wrapping, unlike the plain-list/table-row `:type` handling
            ;; elsewhere in this file, which genuinely is symbol-typed.
            (org-swift--make-node schema-type
              `(("backend" . ,(org-swift--str-or-null (org-swift--prop node :type)))
                ("value" . ,(org-swift--prop node :value)))))

           ('comment-block
            ;; UNTESTED, genuinely: no conformance fixture uses #+begin_comment.
            ;; Passing :value straight through assumes the same trailing-
            ;; newline convention confirmed for src-block/example-block above,
            ;; but that has not actually been exercised for this block type.
            (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ('comment
            ;; CONFIRMED via conformance/easy-comment-line in the 52-case
            ;; clean run: org-element's :value for a `# ...' comment line
            ;; already has the leading "#" and exactly one following space
            ;; stripped (`# this is a comment' -> "this is a comment", not
            ;; "# this is a comment" or " this is a comment").
            (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ('keyword
            ;; Confident (not just assumed): org-element's :value for
            ;; `#+KEY: VALUE' is documented/well-established as just "VALUE",
            ;; already stripped of the "#+KEY: " prefix - this is the one of
            ;; the stripping conventions least likely to need a fix.
            (org-swift--make-node schema-type
              `(("key" . ,(org-swift--prop node :key))
                ("value" . ,(org-swift--prop node :value)))))

           ('horizontal-rule (org-swift--make-node schema-type '()))

           ('fixed-width (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ('statistics-cookie (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))

           ((or 'subscript 'superscript)
            (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('table
            ;; org-element's :type distinguishes an ordinary pipe table
            ;; (`org') from an ASCII-bordered table.el table (`table.el').
            ;; Confirmed live against Emacs 30.2: a table.el table's
            ;; `org-element-contents' is nil (it is never decomposed into
            ;; table-row/table-cell) and its raw text lives in :value
            ;; instead. The ORG case below is byte-identical to what this
            ;; branch always did - SCHEMA.md's `table' node documents only
            ;; the org form, every table in this corpus is org-type, and
            ;; this fix does not add a `kind'/`tableType' field or otherwise
            ;; change that documented shape (an earlier version of this fix
            ;; did add such a field; retracted - that would have been a new
            ;; coverage claim nobody approved, not a bug fix).
            ;;
            ;; table.el is different: it used to fall into the SAME branch
            ;; as org tables, ignoring :type entirely, and silently produced
            ;; `{"type":"table","children":[]}' - valid JSON, exit 0, no
            ;; warning, and schema-valid, so nothing downstream caught the
            ;; lost table text; the single most dangerous gap found in this
            ;; investigation. table.el now gets a LOUD (warns to stderr,
            ;; same convention as an unmapped type), LOSSY (no attempt to
            ;; parse rows/cells - none exist in org-element's own tree
            ;; either), but HONEST (the raw text survives verbatim under
            ;; `value') node instead: `{"type":"table","value":"...",
            ;; "postBlank":...}', which deliberately does NOT match the
            ;; schema's `table' definition (still `children'-only) - this is
            ;; intentional, not an oversight, since a table.el table is not
            ;; something this schema claims to represent yet.
            (if (eq (org-swift--prop node :type) 'table.el)
                (progn
                  (message "org-swift-dump: WARNING: table.el table is not represented by this schema (only org-style pipe tables are) - emitting raw :value, not a schema-conformant table node")
                  (org-swift--make-node schema-type `(("value" . ,(org-swift--prop node :value)))))
              (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node))))))

           ('table-row
            (org-swift--make-node schema-type
              `(("kind" . ,(symbol-name (org-swift--prop node :type)))
                ("children" . ,(org-swift--dump-children node)))))

           ('table-cell (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))

           ('timestamp (org-swift--dump-timestamp node))

           ('footnote-reference
            (let ((inline (eq (org-swift--prop node :type) 'inline)))
              (org-swift--make-node schema-type
                `(("label" . ,(org-swift--str-or-null (org-swift--prop node :label)))
                  ("inline" . ,(org-swift--bool inline))
                  ("children" . ,(if inline (org-swift--dump-children node) org-swift--omit))))))

           ('footnote-definition
            (org-swift--make-node schema-type
              `(("label" . ,(org-swift--prop node :label))
                ;; :pre-blank rationale as headline/item below - confirmed
                ;; live org-element sets it here too (the third and last
                ;; type it tracks this on, alongside headline and item; not
                ;; on inlinetask - not one of this schema's node types - and
                ;; not on anything else: confirmed live paragraph and
                ;; plain-list return nil, i.e. genuinely do not track it).
                ("preBlank" . ,(org-swift--prop node :pre-blank))
                ("children" . ,(org-swift--dump-children node)))))

           (_
            (message "org-swift-dump: WARNING unmapped org-element type: %s" type)
            ;; Hardened fallback (task #23, reviewer's compensating-control
            ;; audit; hardened AGAIN after the C1 crash investigation - and
            ;; corrected once more after that: a first attempt at this fix
            ;; tried recursing into `:value' whenever `(org-element-type
            ;; value)' returned non-nil, reasoning that meant `:value' was
            ;; itself a proper node. That reasoning was tested against nine
            ;; synthetic `:value' shapes and disproved: `org-element-type'
            ;; is a WEAK heuristic (in practice just "is the car of this a
            ;; symbol") that returns non-nil for things that are NOT real
            ;; nodes at all - a dotted cons `(a . b)' or a plain list of
            ;; symbols `(a b)' both satisfy it - so the "recurse" branch
            ;; still crashed on those, just one level deeper, the first time
            ;; the recursive machinery tried to read a property (e.g.
            ;; :post-blank) off data that was never really a node.
            ;; Confirmed live: `org-element-type' itself never errors on any
            ;; of the nine shapes, but `json-serialize' crashes directly on
            ;; a bare symbol, a dotted cons, or a plain (non-vector) Lisp
            ;; list handed to it as a value - exactly the top-of-file
            ;; ambiguity note already warns about never doing.
            ;;
            ;; The fix is a POSITIVE test, not a "does this look like a
            ;; node" guess: only ever hand `:value' to the JSON layer when
            ;; it is `(stringp value)'. Three shapes, tried in order:
            ;;   1. :value is a string -> ordinary leaf, `{"value": ...}'
            ;;      (unchanged from the original fallback).
            ;;   2. :value is nil -> container, `{"children": [...]}'
            ;;      (unchanged) - always safe, since `org-swift--dump-children'
            ;;      reads NODE's own contents, never `value' itself.
            ;;   3. Anything else (a symbol, a cons, a list, a node, a
            ;;      vector, a number - anything non-string, non-nil) -> omit
            ;;      the value entirely rather than guess at its shape, with
            ;;      its own warning distinct from the "unmapped type"
            ;;      message above. This is deliberately the SAME treatment
            ;;      `clock' now gets (no dedicated branch - clock stays an
            ;;      unmapped type on purpose, see the removed branch this
            ;;      comment used to sit next to): loud (warns), lossy (the
            ;;      value is not represented), but never a crash.
            (let ((value (org-swift--prop node :value)))
              (cond
               ((stringp value) (org-swift--make-node schema-type `(("value" . ,value))))
               ((null value) (org-swift--make-node schema-type `(("children" . ,(org-swift--dump-children node)))))
               (t
                (message "org-swift-dump: WARNING unmapped type %s has a non-string, non-nil :value (%S) - omitting it rather than guessing at its shape"
                          type (type-of value))
                (org-swift--make-node schema-type '()))))))))
    ;; Reference-faithful normalization (team decision, post-first-run): the
    ;; normalized tree is org-element's own tree with ONLY buffer positions
    ;; (:begin/:end/:contents-begin/:contents-end) stripped. :post-blank is
    ;; NOT a buffer position - it is a semantic count (blank lines/chars
    ;; org-element itself tracks separately from any content span) - so it is
    ;; kept, as an explicit integer field, on every node, element or object.
    ;; This is what makes finding B's dropped inter-object space
    ;; reconstructible: the space was never in any text value, it lived ONLY
    ;; in the preceding node's :post-blank, confirmed live against Emacs
    ;; (bold's standard-properties vector showed post-blank = 1, and that
    ;; character appears in neither the bold node's children nor the
    ;; following text node). `org-element-property' on :post-blank always
    ;; returns a non-negative integer in practice, but the `(or ... 0)' below
    ;; guards the same nil ambiguity documented on `org-swift--json-array':
    ;; json-serialize has no way to tell Lisp nil apart from an empty value.
    (puthash "postBlank" (or (org-element-property :post-blank node) 0) base)
    ;; Affiliated keywords attach to ELEMENTS only, never to objects -
    ;; `org-swift--affiliated' enforces that itself via TYPE, see its own
    ;; docstring for the fabricated-entity bug this gate fixes.
    (let ((affiliated (org-swift--affiliated node type)))
      (unless (eq affiliated org-swift--omit)
        (puthash "affiliated" affiliated base)))
    base))

(defun org-swift--node-json (node)
  "Convert one org-element NODE - or a bare Lisp string (a `plain-text'
object) or nil - into the JSON-ready Lisp value described at the top of this
file."
  (cond
   ((null node) :null)
   ((stringp node) (org-swift--make-node "text" `(("value" . ,node))))
   ((eq (org-element-type node) 'line-break)
    ;; SCHEMA.md has no dedicated line-break node type: an ordinary soft
    ;; line break inside a paragraph is just an embedded "\n" in whatever
    ;; `text' node spans it, for free, because org-element's own plain-text
    ;; objects already contain that newline verbatim. An EXPLICIT hard break
    ;; (a line ending in "\\") is different: it is its OWN org-element type,
    ;; `line-break', with no properties and no contents of its own, so it
    ;; is flattened here into the same shape a soft break gets: a literal
    ;; `text' node whose value is one newline.
    ;;
    ;; Handled HERE, before `org-swift--dump-typed-node', not as a pcase
    ;; branch inside it (where an earlier version of this lived) - that
    ;; distinction is the fix for a real bug, not a refactor for its own
    ;; sake. `org-swift--dump-typed-node's shared tail code unconditionally
    ;; adds `postBlank' (and attempts `affiliated') to whatever hashtable
    ;; its pcase produces, regardless of what "type" that hashtable actually
    ;; claims to be - so a `line-break' dispatched through that pcase came
    ;; back fabricating a `text' node that DOES carry `postBlank', right
    ;; next to ordinary `text' nodes (built via the `stringp' branch just
    ;; above, which never goes through that tail code) that never carry
    ;; one. Confirmed live against Emacs 30.2: a hard line break used to
    ;; produce `{"type":"text","value":"\n","postBlank":0}' sitting between
    ;; two ordinary `{"type":"text","value":...}' nodes with no such key at
    ;; all - two different shapes for the same node type, which SCHEMA.md
    ;; section 1 says can never happen (a `text' leaf has no `postBlank' key,
    ;; full stop). Building the flattened node directly here, bypassing
    ;; `org-swift--dump-typed-node' entirely, keeps every `text' node in the
    ;; tree the same shape, matching the `stringp' case immediately above.
    (org-swift--make-node "text" '(("value" . "\n"))))
   (t (let* ((type (org-element-type node))
             (schema-type (org-swift--schema-type-name type)))
        (org-swift--dump-typed-node schema-type type node)))))

;; ---------------------------------------------------------------------------
;; Entry point.
;; ---------------------------------------------------------------------------

(defun org-swift-dump (path)
  "Parse the .org file at PATH with `org-element-parse-buffer' and print its
normalized JSON tree (SCHEMA.md shape) to stdout. Intended for
`emacs --batch -Q -l harness/oracle-dump.el --eval \\='(org-swift-dump \"PATH\")\\='.

`coding-system-for-read' is bound to `utf-8' explicitly rather than left to
`--batch' mode's auto-detection, as cheap insurance - though isolated testing
(see below) confirmed `insert-file-contents' was decoding real-world non-ASCII
content correctly even without this, so this is belt-and-suspenders, not the
fix for the bug that was actually found.

The real bug, found live against doomemacs-docs/{appendix,examples,faq}.org
(the first files in this corpus with actual non-ASCII content - a Unicode
ellipsis - every ASCII-only conformance fixture had parsed fine, which is
exactly why this stayed hidden until the real-world corpus ran): `princ`-ing
`json-serialize`'s return value directly corrupted every non-ASCII character
into invalid UTF-8 (bytes like #xC1, which can never appear in well-formed
UTF-8 at all). Root cause, isolated with a minimal reproduction outside this
file entirely: `json-serialize` returns a UNIBYTE string that is already the
raw, correctly-UTF-8-encoded bytes (confirmed correct byte-for-byte via
`mapconcat` over the string's own char codes, bypassing `princ` entirely).
Handing that unibyte byte-string to `princ` in `--batch` mode makes Emacs's
terminal-output layer treat each byte as an eight-bit pseudo-character needing
ITS OWN encoding, so it gets encoded a second time - double-encoding, not a
read-side misdetection. `write-region` to a real file, by contrast, wrote the
exact right bytes immediately - proving `json-serialize` and the parse were
never the problem, only the `princ` step. Neither `coding-system-for-write`
nor `set-terminal-coding-system` fixed it (the latter, tried live, silently
produced zero output in `--batch` mode - it manipulates a terminal that does
not exist there). The fix that worked: `decode-coding-string` the unibyte
result back into a genuine multibyte Lisp string of real characters BEFORE
`princ`, so `princ` re-encodes actual characters instead of re-encoding
already-encoded bytes."
  (unless (file-readable-p path)
    (error "oracle-dump.el: cannot read file: %s" path))
  (let ((coding-system-for-read 'utf-8)
        tree)
    (with-temp-buffer
      (insert-file-contents path)
      ;; `org-mode' must run AFTER the text is inserted so it scans this
      ;; buffer's own `#+TODO:' line (SCHEMA.md rule 2, runtime TODO
      ;; keywords) when it sets up local keyword state - this is the
      ;; two-pass behavior the spec requires, and Emacs already does it for
      ;; free via normal mode activation.
      (org-mode)
      (setq tree (org-element-parse-buffer)))
    (let ((json-value (org-swift--node-json tree)))
      (princ (decode-coding-string (json-serialize json-value) 'utf-8))
      (princ "\n"))))

(provide 'oracle-dump)
;;; oracle-dump.el ends here
