#!/bin/bash
# Regenerates Sources/OrgSwift/EntityNames.swift from the LIVE Emacs org-entities table,
# the same table the oracle consults (org-entities-user is nil under -Q, so the two see
# identical names). Run after an Emacs/org upgrade; commit the diff.
set -euo pipefail
cd "$(dirname "$0")/.."

emacs --batch -Q --eval '(progn
  (require (quote org-entities))
  (princ "// GENERATED by harness/regen-entities.sh -- do not edit by hand.\n")
  (princ "// Source: `org-entities` on the same Emacs the oracle runs (see harness/README).\n")
  (princ "// `org-entities-user` is nil under -Q, matching oracle-dump.el exactly.\n")
  (princ "\n")
  (princ "extension OrgParser {\n")
  (princ "    /// Every name `org-entity-get` can resolve under `-Q`. Membership here is the\n")
  (princ "    /// entity/latex-fragment discriminator for a backslash construct; the six\n")
  (princ "    /// per-entity renderings stay in org'\''s table and are NOT duplicated into the\n")
  (princ "    /// tree (SCHEMA.md, entity).\n")
  (princ "    static let entityNames: Set<String> = [\n")
  (let ((n 0))
    (dolist (e org-entities)
      (when (consp e)
        (setq n (1+ n))
        (princ (format "        %S,\n" (car e)))))
    (princ "    ]\n")
    (princ "}\n")
    (message "regen-entities: %d names" n)))' > Sources/OrgSwift/EntityNames.swift

echo "wrote Sources/OrgSwift/EntityNames.swift"
