#!/usr/bin/env bash
# regen-unicode-classes.sh
#
# Rewrites Sources/OrgSwift/UnicodeClasses.generated.swift from a full-space behavioural
# enumeration: for every valid Unicode scalar S, is S a member of Emacs's `[:alpha:]',
# `[:alnum:]' and `[:word:]' regexp classes in a live org-mode buffer? Takes ~90 seconds -
# this is the REGENERATION path, run on a toolchain bump or when PinnedTableDriftTests
# reports edge drift. The per-test-run gate is the edge probe in that suite, not this sweep.
#
# Usage:
#   bash harness/regen-unicode-classes.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/Sources/OrgSwift/UnicodeClasses.generated.swift"
TSV="$(mktemp)"
trap 'rm -f "$TSV"' EXIT

echo "Enumerating the scalar space (~90s)..." >&2
emacs --batch -Q -l "$ROOT_DIR/harness/pinned-tables.el" \
  --eval '(org-swift-dump-char-classes)' > "$TSV"

VERSIONS="$(emacs --batch -Q -l "$ROOT_DIR/harness/pinned-tables.el" \
  --eval '(princ (format "%s / org-mode %s" emacs-version (org-version)))' 2>/dev/null)"

python3 - "$TSV" "$OUT" "$VERSIONS" <<'EOF'
import sys

tsv, out, versions = sys.argv[1], sys.argv[2], sys.argv[3]
tables = {"ALPHA": [], "ALNUM": [], "WORD": []}
with open(tsv) as f:
    for line in f:
        tag, a, b = line.split()
        assert tag in tables, f"unexpected line: {line!r}"
        tables[tag].append((int(a, 16), int(b, 16)))
for tag, ranges in tables.items():
    assert ranges == sorted(ranges) and ranges, f"{tag} dump must be sorted and non-empty"

names = {"ALPHA": "emacsAlphaRanges", "ALNUM": "emacsAlnumRanges", "WORD": "emacsWordRanges"}
docs = {
    "ALPHA": "`[:alpha:]` members",
    "ALNUM": "`[:alnum:]` members",
    "WORD": "`[:word:]` members (word syntax, so org-mode's syntax table is load-bearing)",
}
lines = [
    "// GENERATED by harness/regen-unicode-classes.sh -- do not edit by hand.",
    "// BEHAVIOURAL ENUMERATION (ORG-17 shape): for every valid Unicode scalar S, is S a member",
    "// of Emacs's `[:alpha:]`, `[:alnum:]` and `[:word:]` regexp classes in a live org-mode",
    "// buffer? Membership lookups live in ParserPrimitives.swift.",
    f"// Emacs {versions}. Drift gate: PinnedTableDriftTests.",
    "",
    "extension OrgParser {",
]
for tag in ("ALPHA", "ALNUM", "WORD"):
    ranges = tables[tag]
    total = sum(b - a + 1 for a, b in ranges)
    lines += [
        f"    /// Emacs {docs[tag]}: {total} scalars in {len(ranges)} closed ranges over the",
        "    /// whole scalar space, sorted and non-overlapping.",
        f"    static let {names[tag]}: [ClosedRange<UInt32>] = [",
    ]
    row = []
    for a, b in ranges:
        row.append(f"0x{a:X}...0x{b:X},")
        if len(row) == 5:
            lines.append("        " + " ".join(row))
            row = []
    if row:
        lines.append("        " + " ".join(row))
    lines += ["    ]", ""]
lines[-1:] = ["}", ""]
with open(out, "w") as f:
    f.write("\n".join(lines))
for tag in ("ALPHA", "ALNUM", "WORD"):
    ranges = tables[tag]
    print(f"{tag}: {len(ranges)} ranges, {sum(b - a + 1 for a, b in ranges)} scalars")
print(f"wrote {out}")
EOF
