#!/usr/bin/env bash
# regen-plain-link-boundary.sh
#
# Rewrites Sources/OrgSwift/PlainLinkBoundary.generated.swift from a full-space behavioural
# enumeration: for every valid Unicode scalar S, does `org-link-plain-re` match immediately
# after S in a live org-mode buffer? Takes ~50 seconds - this is the REGENERATION path, run
# on a toolchain bump or when PinnedTableDriftTests reports edge drift. The per-test-run gate
# is the edge probe in that suite, not this sweep.
#
# Usage:
#   bash harness/regen-plain-link-boundary.sh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT_DIR/Sources/OrgSwift/PlainLinkBoundary.generated.swift"
TSV="$(mktemp)"
trap 'rm -f "$TSV"' EXIT

echo "Enumerating the scalar space (~50s)..." >&2
emacs --batch -Q -l "$ROOT_DIR/harness/pinned-tables.el" \
  --eval '(org-swift-dump-plain-link-boundary)' > "$TSV"

VERSIONS="$(emacs --batch -Q -l "$ROOT_DIR/harness/pinned-tables.el" \
  --eval '(princ (format "%s / org-mode %s" emacs-version (org-version)))' 2>/dev/null)"

python3 - "$TSV" "$OUT" "$VERSIONS" <<'EOF'
import sys

tsv, out, versions = sys.argv[1], sys.argv[2], sys.argv[3]
ranges = []
with open(tsv) as f:
    for line in f:
        tag, a, b = line.split()
        assert tag == "SUPPRESS", f"unexpected line: {line!r}"
        ranges.append((int(a, 16), int(b, 16)))
assert ranges == sorted(ranges) and ranges, "dump must be sorted and non-empty"

lines = [
    "// GENERATED by harness/regen-plain-link-boundary.sh -- do not edit by hand.",
    "// BEHAVIOURAL ENUMERATION (ORG-17 shape): for every valid Unicode scalar S, does",
    "// `org-link-plain-re` match immediately after S in an org-mode buffer? These are the",
    "// ranges where it does NOT -- the scalars that suppress a plain link they precede.",
    f"// Emacs {versions}. Drift gate: PinnedTableDriftTests.",
    "",
    "extension OrgParser {",
    "    /// Scalars after which org forms NO plain link, as closed ranges over the whole",
    "    /// scalar space, sorted and non-overlapping. See `plainLinkBoundarySuppresses`.",
    "    static let plainLinkBoundarySuppressRanges: [ClosedRange<UInt32>] = [",
]
row = []
for a, b in ranges:
    row.append(f"0x{a:X}...0x{b:X},")
    if len(row) == 5:
        lines.append("        " + " ".join(row))
        row = []
if row:
    lines.append("        " + " ".join(row))
lines += ["    ]", "}", ""]
with open(out, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {out}: {len(ranges)} ranges, {sum(b - a + 1 for a, b in ranges)} scalars")
EOF
